# Site settings
title:          天行健，君子以自强不息。<br>地势坤，君子以厚德载物。
description:    
url:            

# Author
author:
  name:         
  email:        
  url:          

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  github: https://github.com/shulthz
  
  
